function TotalEffectCommandLine(A,C,COV,names)

S = regstats(C,[A COV]);
fid = 1;
fprintf(fid,'========= TOTAL EFFECT ===============\n');
fprintf(fid,'Dependent variable: %s\n',names{2});
% print independent variables
Rows = length(S.beta);
%fprintf(fid,'%20s\tUn-Coef\t\tSt-Coef\t\t\n','');
fprintf(fid,'%20s%10s%10s%10s\n','Model','beta','t','p');
fprintf(fid,'%20s','constant');
fprintf(fid,'%10.3f%10.3f%10.4f\n',...
    S.beta(1,1),...
    S.tstat.t(1,1),...
    S.tstat.pval(1,1));

    fprintf(fid,'%20s',names{1});
    fprintf(fid,'%10.3f%10.3f%10.4f\n',...
        S.beta(2),...
        S.tstat.t(2),...
        S.tstat.pval(2));
for j = 3:Rows
        fprintf(fid,'%20s',names{j});
    fprintf(fid,'%10.3f%10.3f%10.4f\n',...
        S.beta(j),...
        S.tstat.t(j),...
        S.tstat.pval(j));
end